#!/usr/bin/env python3
"""Emit swift/MacCleanerKit's target table FROM the Python engine.

The Python table stays the single source of truth until V3 cutover — the
Swift copy is generated, never hand-edited, so transcription drift is
impossible by construction (same reasoning as completions/complete_data.py,
which snapshots the same table for the completion harness).

Paths are emitted HOME-relative ("~/...") by running the engine under a
sentinel HOME; the Swift side re-expands against the live HOME at runtime.
The machine-dependent per-folder `logs` targets are excluded the same way
every other consumer excludes them: the sentinel HOME has no Library/Logs,
so get_targets() generates none.

Regenerate (then rebuild the kit) whenever get_targets() changes:
    python3 tools/gen_swift_target_table.py
"""
import json, os, subprocess, sys, tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "swift" / "MacCleanerKit" / "Sources" / "MacCleanerKit" / "TargetTable.generated.swift"

def main():
    with tempfile.TemporaryDirectory(prefix="mc-swiftgen-") as td:
        home = Path(td) / "home"; home.mkdir()
        code = (
            "import json, sys; sys.path.insert(0, %r)\n"
            "import cleaner\n"
            "cfg = json.loads(json.dumps(cleaner.DEFAULT_CONFIG))\n"
            "cfg['skip_paths'] = []\n"
            "ts = [t for t in cleaner.get_targets(cfg, all_categories=True)\n"
            "      if t['category'] != 'logs']\n"
            "out = []\n"
            "for t in ts:\n"
            "    out.append({'id': t['id'], 'category': t['category'],\n"
            "                'label': t['label'], 'description': t['description'],\n"
            "                'safe': t['safe'], 'empty_only': t['empty_only'],\n"
            "                'cmd': t['cmd'],\n"
            "                'glob': str(t['glob']) if t.get('glob') else None,\n"
            "                'paths': [str(p) for p in (t.get('paths') or ([t['path']] if t.get('path') else []))]})\n"
            "print(json.dumps({'categories': {c: cleaner.CATEGORY_DESCRIPTIONS[c] for c in cleaner.ALL_CATEGORIES},\n"
            "                  'targets': out}))\n"
        ) % str(REPO)
        r = subprocess.run([sys.executable, "-c", code],
                           capture_output=True, text=True, timeout=120,
                           env={**os.environ, "HOME": str(home)})
        if r.returncode != 0:
            sys.stderr.write(r.stderr); raise SystemExit(1)
        data = json.loads(r.stdout)

    def rel(p):
        s = str(home)
        return p.replace(s, "~") if p.startswith(s) else p

    def slit(s):
        if s is None:
            return "nil"
        # ensure_ascii=False: JSON's \uXXXX escapes are not Swift syntax
        # (Swift wants \u{XXXX}); raw UTF-8 in a Swift source file is fine,
        # and the remaining escapes (\" \\ \n \t) are shared syntax.
        return json.dumps(s, ensure_ascii=False)

    lines = [
        "// GENERATED by tools/gen_swift_target_table.py — DO NOT EDIT.",
        "// The Python engine's get_targets() is the source of truth until V3 cutover;",
        "// regenerate this file (and re-run tools/check_swift_parity.py) after any",
        "// target change. tests/test_cleaner.py's TestSwiftTableGenerated pins freshness.",
        "",
        "public let categoryDescriptions: [(name: String, description: String)] = [",
    ]
    for name, desc in data["categories"].items():
        lines.append(f"    (name: {slit(name)}, description: {slit(desc)}),")
    lines += ["]", "", "public let allTargets: [Target] = ["]
    for t in data["targets"]:
        paths = ", ".join(slit(rel(p)) for p in t["paths"])
        lines.append(
            f"    Target(id: {slit(t['id'])}, category: {slit(t['category'])}, "
            f"label: {slit(t['label'])}, desc: {slit(t['description'])}, "
            f"safe: {'true' if t['safe'] else 'false'}, "
            f"emptyOnly: {'true' if t['empty_only'] else 'false'}, "
            f"paths: [{paths}], glob: {slit(rel(t['glob']) if t['glob'] else None)}, "
            f"cmd: {slit(t['cmd'])}),")
    lines.append("]")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(data['targets'])} targets -> {OUT.relative_to(REPO)}")

if __name__ == "__main__":
    main()
